// src/utils/pdfExport.js
// PDF report generation using jsPDF + autoTable
// Install: npm install jspdf jspdf-autotable
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Brand colors ─────────────────────────────────────────────────────────────
const BRAND = {
  primary: [37, 99, 235],    // blue-600
  dark: [15, 15, 15],
  gray: [107, 114, 128],
  lightGray: [243, 244, 246],
  success: [34, 197, 94],
  warning: [234, 179, 8],
  danger: [239, 68, 68],
};

function addHeader(doc, title, subtitle) {
  // Dark header bar
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, 210, 28, 'F');

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('AtomQuest', 14, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text('Goal Management Portal', 14, 18);

  // Title on right
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(title, 210 - 14, 12, { align: 'right' });

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(subtitle, 210 - 14, 18, { align: 'right' });
  }

  // Blue accent line
  doc.setFillColor(...BRAND.primary);
  doc.rect(0, 28, 210, 1.5, 'F');
}

function addFooter(doc, pageNumber) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFillColor(243, 244, 246);
  doc.rect(0, pageHeight - 12, 210, 12, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.gray);
  doc.text(
    `Generated by AtomQuest Goal Portal · ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`,
    14,
    pageHeight - 4
  );
  doc.text(`Page ${pageNumber}`, 210 - 14, pageHeight - 4, { align: 'right' });
}

function statusColor(status) {
  switch (status) {
    case 'completed': return [34, 197, 94];
    case 'on_track': return [59, 130, 246];
    case 'at_risk': return [239, 68, 68];
    case 'approved': return [34, 197, 94];
    case 'pending_approval': return [234, 179, 8];
    default: return [107, 114, 128];
  }
}

function progressBar(doc, x, y, width, progress) {
  const height = 4;
  doc.setFillColor(229, 231, 235);
  doc.roundedRect(x, y, width, height, 1, 1, 'F');
  const filled = Math.min((progress / 100) * width, width);
  const color = progress >= 70 ? BRAND.success : progress >= 40 ? BRAND.warning : BRAND.danger;
  doc.setFillColor(...color);
  if (filled > 0) doc.roundedRect(x, y, filled, height, 1, 1, 'F');
}

// ─── 1. Goal Achievement Report ──────────────────────────────────────────────
export function exportGoalAchievementReport(goals = [], meta = {}) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const { employeeName = 'All Employees', period = 'Q2 2025' } = meta;

  addHeader(doc, 'Goal Achievement Report', `${employeeName} · ${period}`);

  // Summary stats
  const total = goals.length;
  const completed = goals.filter((g) => g.status === 'completed').length;
  const onTrack = goals.filter((g) => g.status === 'on_track').length;
  const atRisk = goals.filter((g) => g.status === 'at_risk').length;
  const avgProgress = total > 0
    ? Math.round(goals.reduce((sum, g) => sum + (g.progress || 0), 0) / total)
    : 0;

  let y = 36;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.dark);
  doc.text('SUMMARY', 14, y);

  y += 5;
  const summaryData = [
    ['Total Goals', total, 'Completed', completed, 'On Track', onTrack, 'At Risk', atRisk, 'Avg Progress', `${avgProgress}%`],
  ];

  const cardWidth = (297 - 28 - 8 * 4) / 5;
  [
    { label: 'Total Goals', value: total, color: BRAND.dark },
    { label: 'Completed', value: completed, color: BRAND.success },
    { label: 'On Track', value: onTrack, color: BRAND.primary },
    { label: 'At Risk', value: atRisk, color: BRAND.danger },
    { label: 'Avg Progress', value: `${avgProgress}%`, color: BRAND.primary },
  ].forEach((card, i) => {
    const cx = 14 + i * (cardWidth + 4);
    doc.setFillColor(...BRAND.lightGray);
    doc.roundedRect(cx, y, cardWidth, 16, 2, 2, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...card.color);
    doc.text(String(card.value), cx + cardWidth / 2, y + 10, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(...BRAND.gray);
    doc.text(card.label, cx + cardWidth / 2, y + 14, { align: 'center' });
  });

  y += 22;

  // Main table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Goal Title', 'Thrust Area', 'UoM', 'Weight', 'Target', 'Actual', 'Progress', 'Status']],
    body: goals.map((g, i) => [
      i + 1,
      g.title || '—',
      g.thrustArea || '—',
      g.uom || '—',
      `${g.weightage || 0}%`,
      String(g.target || '—'),
      String(g.actual || '—'),
      `${g.progress || 0}%`,
      (g.status || 'draft').replace(/_/g, ' '),
    ]),
    styles: { fontSize: 8, cellPadding: 3, font: 'helvetica' },
    headStyles: { fillColor: BRAND.dark, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 65 },
      4: { halign: 'center' },
      7: { halign: 'center', fontStyle: 'bold' },
    },
    didDrawCell: (data) => {
      // Draw mini progress bar in Progress column (index 7)
      if (data.column.index === 7 && data.section === 'body') {
        const goal = goals[data.row.index];
        if (!goal) return;
        const { x, y: cellY, width, height } = data.cell;
        progressBar(doc, x + 1, cellY + height / 2, width - 2, goal.progress || 0);
        data.cell.text = ['']; // hide text — bar replaces it
      }
      if (data.column.index === 8 && data.section === 'body') {
        const goal = goals[data.row.index];
        if (!goal) return;
        const color = statusColor(goal.status);
        const { x, y: cellY, width, height } = data.cell;
        const text = (goal.status || 'draft').replace(/_/g, ' ');
        doc.setFillColor(...color.map((c) => Math.min(c + 180, 255)));
        doc.roundedRect(x + 1, cellY + 1.5, width - 2, height - 3, 1.5, 1.5, 'F');
        doc.setTextColor(...color);
        doc.setFontSize(6.5);
        doc.setFont('helvetica', 'bold');
        doc.text(text, x + width / 2, cellY + height / 2 + 0.5, { align: 'center', baseline: 'middle' });
        data.cell.text = [''];
      }
    },
    margin: { left: 14, right: 14 },
    theme: 'plain',
  });

  addFooter(doc, 1);
  doc.save(`AtomQuest_GoalAchievement_${period.replace(/\s+/g, '_')}.pdf`);
}

// ─── 2. Team Progress Report ──────────────────────────────────────────────────
export function exportTeamProgressReport(teamData = [], managerName = 'Manager') {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  addHeader(doc, 'Team Progress Report', `${managerName} · ${new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}`);

  autoTable(doc, {
    startY: 35,
    head: [['Employee', 'Dept', 'Goals', 'Avg Progress', 'Completed', 'At Risk', 'Last Check-in']],
    body: teamData.map((member) => [
      member.name || '—',
      member.department || '—',
      member.totalGoals || 0,
      `${member.avgProgress || 0}%`,
      member.completed || 0,
      member.atRisk || 0,
      member.lastCheckin
        ? new Date(member.lastCheckin).toLocaleDateString('en-IN')
        : 'Never',
    ]),
    styles: { fontSize: 9, cellPadding: 3.5, font: 'helvetica' },
    headStyles: { fillColor: BRAND.dark, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 14, right: 14 },
    theme: 'plain',
  });

  addFooter(doc, 1);
  doc.save(`AtomQuest_TeamProgress_${managerName.replace(/\s+/g, '_')}.pdf`);
}

// ─── 3. Escalation Log Export ─────────────────────────────────────────────────
export function exportEscalationLog(escalations = []) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  addHeader(doc, 'Escalation Log', `Admin Export · ${new Date().toLocaleDateString('en-IN')}`);

  autoTable(doc, {
    startY: 35,
    head: [['Severity', 'Employee', 'Goal', 'Rule', 'Reason', 'Level', 'Escalated', 'Status']],
    body: escalations.map((e) => [
      e.severity?.toUpperCase() || '—',
      e.employeeName || '—',
      e.goalTitle || '—',
      e.ruleName || '—',
      e.reason || '—',
      e.level || '—',
      e.escalatedAt ? new Date(e.escalatedAt).toLocaleDateString('en-IN') : '—',
      e.status || '—',
    ]),
    styles: { fontSize: 7.5, cellPadding: 2.5, font: 'helvetica' },
    headStyles: { fillColor: BRAND.dark, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      0: { fontStyle: 'bold' },
      4: { cellWidth: 60 },
    },
    margin: { left: 14, right: 14 },
    theme: 'plain',
  });

  addFooter(doc, 1);
  doc.save('AtomQuest_EscalationLog.pdf');
}

// ─── Convenience: export button wrapper ──────────────────────────────────────
// import { exportGoalAchievementReport } from '../../utils/pdfExport';
//
// <button
//   onClick={() => exportGoalAchievementReport(goals, { employeeName: user.displayName, period: 'Q2 2025' })}
//   className="flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-xl text-sm font-semibold hover:bg-red-700 transition-colors"
// >
//   <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
//     <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
//     <polyline points="14 2 14 8 20 8"/><line x1="12" y1="18" x2="12" y2="12"/>
//     <line x1="9" y1="15" x2="15" y2="15"/>
//   </svg>
//   Export PDF
// </button>